# Generated by Django 3.1.5 on 2021-01-12 16:25

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('sku', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=-2147483648), django.core.validators.MaxValueValidator(limit_value=2147483648)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=512)),
            ],
        ),
    ]
